server:
  port: 8080


spring:
  application:
    name: Airline-Reservation-System
  datasource:
    url: jdbc:mysql://localhost:3306/ars_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
